import type { Flight } from './types'

export const mockFlights: Flight[] = [
  // Arrivals
  {
    id: '1',
    type: 'arrival',
    tailNumber: 'N525JT',
    aircraftType: 'Gulfstream G550',
    origin: 'KTEB',
    scheduledTime: '14:30',
    scheduledDate: new Date().toISOString().split('T')[0],
    duration: 90,
    actualTime: '14:25',
    status: 'arrived',
    pilot: 'John Smith',
    passengers: 6,
    services: ['fuel', 'hangar', 'catering'],
    notes: 'VIP passenger onboard',
    source: 'qt',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T14:25:00Z'
  },
  {
    id: '2',
    type: 'arrival',
    tailNumber: 'N847PA',
    aircraftType: 'Citation X',
    origin: 'KMIA',
    scheduledTime: '15:45',
    scheduledDate: new Date().toISOString().split('T')[0],
    duration: 60,
    status: 'en-route',
    pilot: 'Sarah Johnson',
    passengers: 4,
    services: ['fuel', 'ground_transport'],
    source: 'calendar',
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: '2025-01-15T13:00:00Z'
  },
  {
    id: '3',
    type: 'arrival',
    tailNumber: 'N123AB',
    aircraftType: 'King Air 350',
    origin: 'KBOS',
    scheduledTime: '16:15',
    scheduledDate: new Date().toISOString().split('T')[0],
    duration: 75,
    status: 'delayed',
    pilot: 'Mike Davis',
    passengers: 8,
    services: ['fuel', 'maintenance'],
    notes: 'Weather delay - 30 minutes',
    source: 'manual',
    createdAt: '2025-01-15T11:00:00Z',
    updatedAt: '2025-01-15T14:00:00Z'
  },
  {
    id: '4',
    type: 'arrival',
    tailNumber: 'N789XY',
    aircraftType: 'Challenger 350',
    origin: 'KORD',
    scheduledTime: '17:00',
    scheduledDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    duration: 120,
    status: 'scheduled',
    pilot: 'Emily Chen',
    passengers: 5,
    services: ['fuel', 'hangar', 'catering', 'ground_transport'],
    source: 'qt',
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2025-01-15T08:00:00Z'
  },
  {
    id: '5',
    type: 'arrival',
    tailNumber: 'N456CD',
    aircraftType: 'Phenom 300',
    origin: 'KDCA',
    scheduledTime: '18:30',
    scheduledDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    duration: 45,
    status: 'scheduled',
    pilot: 'Robert Lee',
    passengers: 3,
    services: ['fuel'],
    source: 'calendar',
    createdAt: '2025-01-15T12:00:00Z',
    updatedAt: '2025-01-15T12:00:00Z'
  },

  // Departures
  {
    id: '6',
    type: 'departure',
    tailNumber: 'N321GH',
    aircraftType: 'Falcon 7X',
    destination: 'KLAX',
    scheduledTime: '13:00',
    scheduledDate: new Date().toISOString().split('T')[0],
    duration: 90,
    actualTime: '13:05',
    status: 'departed',
    pilot: 'David Wilson',
    passengers: 7,
    services: ['fuel', 'catering'],
    source: 'qt',
    createdAt: '2025-01-14T16:00:00Z',
    updatedAt: '2025-01-15T13:05:00Z'
  },
  {
    id: '7',
    type: 'departure',
    tailNumber: 'N654IJ',
    aircraftType: 'Citation Latitude',
    destination: 'KPBI',
    scheduledTime: '15:00',
    scheduledDate: new Date().toISOString().split('T')[0],
    duration: 60,
    status: 'scheduled',
    pilot: 'Lisa Martinez',
    passengers: 6,
    services: ['fuel', 'ground_transport'],
    source: 'manual',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z'
  },
  {
    id: '8',
    type: 'departure',
    tailNumber: 'N987KL',
    aircraftType: 'Global 6000',
    destination: 'EGLL',
    scheduledTime: '16:30',
    scheduledDate: new Date(Date.now() + 172800000).toISOString().split('T')[0],
    duration: 150,
    status: 'scheduled',
    pilot: 'James Brown',
    passengers: 10,
    services: ['fuel', 'hangar', 'catering', 'maintenance'],
    notes: 'International flight - customs required',
    source: 'qt',
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: '2025-01-15T09:00:00Z'
  },
  {
    id: '9',
    type: 'departure',
    tailNumber: 'N246MN',
    aircraftType: 'Hawker 900XP',
    destination: 'KAUS',
    scheduledTime: '17:45',
    scheduledDate: new Date(Date.now() + 259200000).toISOString().split('T')[0],
    duration: 75,
    status: 'scheduled',
    pilot: 'Amanda White',
    passengers: 4,
    services: ['fuel'],
    source: 'calendar',
    createdAt: '2025-01-15T11:00:00Z',
    updatedAt: '2025-01-15T11:00:00Z'
  },
  {
    id: '10',
    type: 'departure',
    tailNumber: 'N135OP',
    aircraftType: 'Premier 1A',
    destination: 'KSEA',
    scheduledTime: '19:00',
    scheduledDate: new Date().toISOString().split('T')[0],
    duration: 60,
    status: 'cancelled',
    pilot: 'Chris Taylor',
    passengers: 2,
    services: [],
    notes: 'Cancelled due to mechanical issue',
    source: 'manual',
    createdAt: '2025-01-15T13:00:00Z',
    updatedAt: '2025-01-15T14:30:00Z'
  },
  {
    id: '11',
    type: 'departure',
    tailNumber: 'N802QR',
    aircraftType: 'Learjet 75',
    destination: 'KDEN',
    scheduledTime: '20:15',
    scheduledDate: new Date(Date.now() + 345600000).toISOString().split('T')[0],
    duration: 90,
    status: 'scheduled',
    pilot: 'Nicole Garcia',
    passengers: 5,
    services: ['fuel', 'catering', 'ground_transport'],
    source: 'qt',
    createdAt: '2025-01-15T12:00:00Z',
    updatedAt: '2025-01-15T12:00:00Z'
  }
]
