# Generated by Django 5.1.4 on 2025-08-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, help_text='Внешний идентификатор из внешней базы', max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Номер счета')),
                ('invoice_date', models.DateField(db_index=True, verbose_name='Дата счета')),
                ('invoice_type', models.CharField(choices=[('purchase', 'Закупка'), ('sale', 'Продажа')], db_index=True, default='purchase', max_length=20, verbose_name='Тип счета')),
                ('sale_type', models.CharField(blank=True, choices=[('stock', 'Со склада'), ('order', 'Под заказ')], db_index=True, max_length=20, null=True, verbose_name='Тип продажи')),
                ('currency', models.CharField(choices=[('RUB', 'Рубли'), ('USD', 'Доллары США'), ('CNY', 'Китайские юани')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, help_text='Внешний идентификатор из внешней базы', max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в валюте счета')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.invoice', verbose_name='Счет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Строка в счете',
                'verbose_name_plural': 'Строки в счетах',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type', 'sale_type'], name='sales_invoi_invoice_1d799a_idx'),
        ),
    ]
