# Generated by Django 5.1.4 on 2025-08-11 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, help_text='Внешний идентификатор из внешней базы', max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, help_text='Внешний идентификатор из внешней базы', max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название бренда')),
                ('product_manager', models.ForeignKey(blank=True, help_text='Менеджер, отвечающий за данный бренд', limit_choices_to={'role': 'product'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер за бренд')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='ProductSubgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, help_text='Внешний идентификатор из внешней базы', max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название подгруппы')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='goods.productgroup', verbose_name='Группа товаров')),
                ('product_manager', models.ForeignKey(blank=True, help_text='Менеджер, отвечающий за данную подгруппу', limit_choices_to={'role': 'product'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_subgroups', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
            ],
            options={
                'verbose_name': 'Подгруппа товаров',
                'verbose_name_plural': 'Подгруппы товаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, help_text='Внешний идентификатор из внешней базы', max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Part number')),
                ('tech_params', models.JSONField(blank=True, default=dict, help_text='Технические характеристики товара в формате JSON', verbose_name='Технические параметры')),
                ('complex_name', models.CharField(help_text='Комплексное наименование товара', max_length=512, verbose_name='Комплексное наименование')),
                ('description', models.TextField(blank=True, help_text='Описание товара', verbose_name='Описание')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='goods.brand', verbose_name='Бренд')),
                ('product_manager', models.ForeignKey(blank=True, help_text='Если не указан, используется менеджер бренда или подгруппы', limit_choices_to={'role': 'product'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='goods.productsubgroup', verbose_name='Подгруппа')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
